services:
  bot_env:
    build: ./docker
    ports:
      - "8080:8080"
    volumes:
      - ./docker/src:/app/src
      - ./docker/main.py:/app/main.py
      - ./docker/two_player_games:/app/two_player_games
    environment:
      - PYTHONUNBUFFERED=1
      - IN_DOCKER=true

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/tests:/app/tests
    environment:
      - PYTHONUNBUFFERED=1
      - IN_DOCKER=true
      - MONGODB_URI=mongodb://mongodb:27017/
      - BOT_ENV=http://bot_env:8080/
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src
      - ./frontend/tests:/app/tests
    environment:
      - IN_DOCKER=true
    depends_on:
      - backend
